[env]
DATABASE_URL = "{{ exec(command=config_root ~ '/../scripts/db-url api-service dev') }}"
TEST_DATABASE_URL = "{{ exec(command=config_root ~ '/../scripts/db-url api-service test') }}"
_.file = ['.env', '.env.local']
