# Changes here will be overwritten by Copier
_commit: v0.6.5
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: false
description: Copier template repository for generating GitHub Actions workflows and
    project scaffolding.
is_public: true
project_name: generic-boilerplate
release_type: simple
repo_language: en
subpackages: []
type: base
use_release_please: true
