[env]
DATABASE_URL = "{{ exec(command=config_root ~ '/../scripts/db-url frontend dev') }}"
TEST_DATABASE_URL = "{{ exec(command=config_root ~ '/../scripts/db-url frontend test') }}"
_.file = ['.env', '.env.local']
