issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte(@11088009)?/generic-boilerplate(@996201414)?:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/generic-boilerplate/\.github/workflows/sync-generated-to-template\.yml@[^@]+$
permissions:
  contents: write
